version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: GitHub-actions
    directory: "/"
    schedule:
      interval: monthly
